### ISSUE TITLE
Upgrade to Joomla 3.6.5

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-platform-content#34]
See: https://github.com/joomlatools/joomlatools-platform/issues/315

**Comment by allanpilarca** [comment]
I tried to change the dependency to use the branch for this ticket but it keeps returning some errors like:
```
- joomlatools/platform-content dev-feature/34-joomla-3.6.5-upgrade requires joomlatools/platform-categories dev-feature/19-joomla-3.6.5-upgrade -> satisfiable by joomlatools/platform-categories[dev-feature/19-joomla-3.6.5-upgrade] but these conflict with your requirements or minimum-stability
- joomlatools/platform-content dev-feature/34-joomla-3.6.5-upgrade requires joomlatools/platform-categories dev-feature/19-joomla-3.6.5-upgrade -> satisfiable by joomlatools/platform-categories[dev-feature/19-joomla-3.6.5-upgrade] but these conflict with your requirements or minimum-stability
- Installation request for joomlatools/platform-content dev-feature/34-joomla-3.6.5-upgrade -> satisfiable by joomlatools/platform-content[dev-feature/34-joomla-3.6.5-upgrade].
```

I also tried chaging the minimum-stability for specific package to dev but still receiving that error. So i temporarily remove the dependency for platform-content and platform-categories and just require those in the platform package.

To test this run this in your platform directory:
```shell
composer require joomlatools/platform-legacy:dev-feature/17-joomla-3.6.5-upgrade
composer require joomlatools/platform-categories:dev-feature/19-joomla-3.6.5-upgrade
composer require joomlatools/platform-content:dev-feature/34-joomla-3.6.5-upgrade
```
@stevenrombauts is there a better/correct way of doing this? (changing the the dependency to a specific branch)

**Comment by stevenrombauts** [comment]
@allanpilarca Unfortunately, there isn't a better way to do this. When testing an install you need to update _all_ dependencies that you require if you are testing development versions to point to the right branch, for example. I thought about scripting this but the set up changes each time as well. I do the same as you did now.
